version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: habr
      POSTGRES_USER: habr
    network_mode: host
